### ISSUE TITLE
Class Notes

### ISSUE THREAD

**Issue by beardofedu** [githubteacher/developers-july-PM#115]
### Getting Started
**Quick review of what we've covered so far:**
- Repository for Class: https://github.com/githubteacher/developers-july-PM
- Tour of Repository: 
  - Code View:  Files belonging to the project
  - README.md: Description of the Repository 
  - Issues: A place to have conversations and collaborate
  - Pull requests: A place to collaborate while introducing changes to your project
- Comment on [this issue](https://github.com/githubteacher/developers-july-PM/issues/2) to become a collaborator on the project
- Practice making an issue [in the issues tab of the class repository](https://github.com/githubteacher/developers-july-PM/issues).
  - For today's activity, be sure to include your username in the title, like "YourUserName Hometown"
  - In the body of the issue, we added the steps we'll take for the workflow. 
  - Our goal later will be to add a document with information about your hometown, like good restaurants or things to do. 
  - You can include [markdown](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) syntax here.

**Getting access to the collaborator script:**
The collaborator script is open-source! You can access it [here](https://github.com/github/training-utils). Our [training kit](https://github.com/github/training-kit) is also open-source. We invite you to use these and welcome contributions to both these repos!

### GitHub Flow
**You can find that visual of the GitHub flow at this link:** https://guides.github.com/introduction/flow/

### Branching with Git
**Review of branches**
- When you create a branch, you are essentially creating an identical copy of the project at that point in time that is completely separate from the master branch.
- Create a branch on GitHub.com in the class repository
  - Click the 'branch' dropdown 
  - Enter a branchname name 'firstname-lastname-hometown'

### Local Git Configs
**Review of configurations:**
- We determined our git version by running `git --version`... version 1.9+ is recommended
- If you need to, you can install it [here](https://git-scm.com/)
- If you don't already have GitHub Desktop, you can install it [here](https://desktop.github.com/)
- Clone the repository by running `git clone https://github.com/githubteacher/developers-july-PM.git` (Make sure you are in the directory where you want the repository to be when you run this command)
- Set up your Git configurations by running these commands:
  - `git config --global user.name "your name"`
  - `git config --global user.email <youremail@email.com>`
  - `git config --global core.editor <editor>` (For more help associating your text editor with Git, read [this GitHub Help article](https://help.github.com/articles/associating-text-editors-with-git/).
  - `git config --global push.default simple`
  - Windows ONLY: `git config --global core.autocrlf true`
  - Mac and Linux ONLY: `git config --global core.autocrlf input`
- Check your configurations by running `git config --list`

**Comment by beardofedu** [comment]
### Working Locally
**Review of working locally**
- Working on our new branch, we created a new file.
- List the files in your current directory by running `ls -la`
- We learned about 'working', 'staging', and 'history' and how commits fit into those areas using [this resource](https://services.github.com/kit/modules/CONT-CLI-04_Two_Stage_Commit.html).
- See your working/staged area  `git status`. This command is :heart:! 
 
   1. Change your file from 'working' to 'staging' by running `git add <file-name>`
   2. Change your file from 'staging' to 'history' by running `git commit`
   3. Text editor opens: Write a 'commit message' tells a story of the changes you just made in 50 characters or less.

- Create a new file and repeat steps 1 - 3 for the two stage commit. This way, we'll have two commits to work with.
- Here are some shortcuts to know about in the future:
  - To automatically stage all files that have been changed, run `git add -A`. Note: This will only work for files that are already being tracked, not brand new files.
  - Avoid the text editor in the commit by running `git commit -m "commit message"`

**Comment by beardofedu** [comment]
### Collaborating on Code
**Review of moving from Git to GitHub**
- We talked about _remote_, and how we can see details about it by running `git remote`, `git remote -v`, and `git remote show origin`
- 'Push' our changes on the current branch to GitHub.com by running `git push -u origin <branch-name>`
- If you forget the `-u` tag, set a 'upstream branch' relationship between our local branch and the GitHub.com remote branch by running `git branch --set-upstream-to=origin/<remote-branch-name>`
  - This means we only have to run `git push` and `git pull` in the future
    - git pull is the combination of git fetch and git merge
- `git branch` and `git branch -a` will help you see what is going on with your local and remote branches
- On GitHub.com, open a pull request in our [class repository](https://github.com/githubteacher/github-for-developers-2016-04) by clicking the green "New pull request" button.
  - Make sure your pull request says `base: master` and `compare: <your-new-branch>`
  - Give it a good title and message about the changes you introduced. Bonus points for using [markdown](https://guides.github.com/features/mastering-markdown/) and emojis!
  - You can add labels and assignees to pull requests like we did with Issues.
- Using @mention is important - you can mention people or teams to give them a notification to see your pull request to start collaboration.

**Notifications**
- Notifications are an important part of GitHub. You can customize these several ways.
  - For GitHub in general, [Settings/notificatons](https://github.com/settings/notifications)
  - For repositories, at the top of a repository page on GitHub.com by clicking "Watch"
  - For individual issues and pull requests by clicking "unsubscribe" on the right hand side of the webpage
- On the pull request page, we talked about the different tabs for 'conversation', 'commits', and 'files changed'.
  - 'Conversation' is where you and your colleagues can collaborate on your changes. This view includes comments as well as notes of when changes happen.
  - 'Commits' shows a history of what commits were added - this is why your commit messages matter - they tell a story.
  - 'Files changed' will let you see the actual code in several different formats. You also can make line level comments from this view.

### Edit on GitHub
**How to edit a file on GitHub**
- To edit a pull request file, you use the `files changed` view and click the `edit` icon.
- Once you've made changes, create a new commit on the bottom of the page. 
- Make sure you commit to the correct branch

### Merging Pull Requests
**Pull requests**
- During class, please do not close or merge any pull requests other than your own.
- On your own pull request, if all is green and there are no conflicts, go ahead and merge your branch.
- After merging a branch, it's part of the `master` branch and good practice is to delete it.
  - This is a major difference between Git and some older version control systems. In Git, branch often, merge often, and delete branches often.
- Back at the command line, we need to pull down the changes from GitHub.com in the remote repository.
   - `git checkout master`
   - `git pull`
   - `git branch --merged`
   - `git branch -d <branch-name>`
   - `git fetch --prune`
- Configure your settings to do this by default by typing `git config --global fetch.prune true`

### View Local Changes
**Local Diffs**
- View local diff diagram [here](https://services.github.com/kit/modules/CONT-CLI-11_Viewing-local-diffs.html)
- `git diff`: See local changes between working, staging, and history
- If we have added more changes to a file that we've already created, we can see differences between them with `git diff`
- Add to a file just for this example: `echo "Here is one line of text" >> file2.md`
- See status: `git status`
- Stage the file: `git add .`
- `git commit -m "commit message"`
- See status: `git status`
- Add more text: `echo "Here is another line of text" >> file2.md`
- Stage: `git add .`
- More text: `echo "Third line of text" >> file2.md`
- See differences with `git diff`
  - `git diff`
  - `git diff --staged`
  - `git diff HEAD`

### Local History
- Use `git log` to view the history of the repository
- `git log` will show commits from your own local repository, but also changes made by other collaborators 
- Experiment with different option switches to view history:
  - `git log`
  - `git log --oneline`
  - `git log --oneline --graph`
  - `git log --oneline --graph --decorate`
  - `git log --oneline --graph --decorate --all`
  - `git log --stat`
  - `git log --patch`
- Use the up and down arrows or press enter to view additional log entries. Type q to quit viewing the log and return to the command prompt.

### Fixing Commit Mistakes
- Change a commit message with `git commit --amend`

### Streamline Workflow With Aliases
- Set up an alias in configurations: `git config --global alias.<desired-alias> "the long version of the command that you want the alias to run, without git at the beginning, and with the desired flags"`

**Comment by humburgc** [comment]
Thanks!!
